<a href="https://colab.research.google.com/github/TanishaSharma01/ml/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy - Numerical Python**

Advantages of Numpy Arrays:
1. Allows several mathematical operations
2. Faster operations

In [2]:
import numpy as np


List vs Numpy - Time taken


In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010966319999998753


Time taken by numpy aray

In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0010652330000000543


Numpy Arrays

In [6]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
# creating a 2 dim array
b = np.array([(1,2,3,4),(6,7,8,9)])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [11]:
c = np.array([(1,2,3),(4,5,6)], dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


Initial Placeholders in Numpy array

In [12]:
# create array with all zeros
# mention in brackets the shape of your array
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((3,2),5)
print(z)

[[5 5]
 [5 5]
 [5 5]]


In [15]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.91702202 0.24643483 0.0125742  0.11101945]
 [0.7952997  0.60493479 0.99759829 0.8615614 ]
 [0.15876347 0.67932756 0.16423961 0.18698284]]


In [17]:
# create a numpy array with random integers
c = np.random.randint(10,100,(3,5))
print(c)

[[36 65 54 47 48]
 [13 23 13 70 37]
 [15 19 35 76 88]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [19]:
# array of evenly spaced values --> specifying the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analyzing a Numpy Array

In [24]:
c = np.random.randint(10, 90, (5,5))
print(c)

[[50 40 36 13 78]
 [71 77 45 74 71]
 [23 36 46 71 33]
 [59 78 16 58 28]
 [24 16 64 56 47]]


In [25]:
print(c.shape)

(5, 5)


In [26]:
# number of dimensions
print(c.ndim)

2


In [28]:
# number of elements in an array
print(c.size)

25


In [29]:
# checking the data type of the values of the array
print(c.dtype)

int64


Mathematical operations on an np array

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) #concatenates or joins two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(10, 20, (3,3))

In [33]:
print(a)
print(b)

[[0 9 0]
 [3 3 3]
 [9 3 5]]
[[15 14 15]
 [13 11 16]
 [16 12 14]]


In [36]:
print(a+b) # summed up the values of the two arrays
print(a-b)
print(a*b)
print(a/b)

[[15 23 15]
 [16 14 19]
 [25 15 19]]
[[-15  -5 -15]
 [-10  -8 -13]
 [ -7  -9  -9]]
[[  0 126   0]
 [ 39  33  48]
 [144  36  70]]
[[0.         0.64285714 0.        ]
 [0.23076923 0.27272727 0.1875    ]
 [0.5625     0.25       0.35714286]]


In [40]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 23 15]
 [16 14 19]
 [25 15 19]]
[[-15  -5 -15]
 [-10  -8 -13]
 [ -7  -9  -9]]
[[  0 126   0]
 [ 39  33  48]
 [144  36  70]]
[[0.         0.64285714 0.        ]
 [0.23076923 0.27272727 0.1875    ]
 [0.5625     0.25       0.35714286]]


Array Manipulation

In [42]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 1 0]
 [6 9 8]]
(2, 3)


In [43]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 6]
 [1 9]
 [0 8]]
(3, 2)


In [45]:
# transpose 2
trans2 = array.T
print(trans2)

[[9 6]
 [1 9]
 [0 8]]


In [47]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 6 3]
 [1 2 6]]
(2, 3)


In [48]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 6]
 [3 1]
 [2 6]]
(3, 2)
